### ISSUE TITLE
image sliding not working on jquery ui dialogs

### ISSUE THREAD

**Issue by mericano1** [benhoIIand/Slidorion#10]
Hi,
I've been trying to use the plugin in a jquery UI dialog that is loaded using an ajax call. The accordion works fine but the images are not sliding.
I found out the problem is in 109 - 111

```
$(window).load(function(){
  loaded = true;
});
```

i guess because the page is already loaded that event is never fired. Even if I manually trigger the event

```
$(window).trigger('onload');
```

nothing changes.

Removing the check in the animation function fixes the issue. 

The question is...does it make sense to start the accordion but not the slides until the page is loaded?

**Comment by benhoIIand** [comment]
I hadn't noticed that the accordion isn't checked. I will add a check on both the slides and accordion now. thanks for the heads up

**Comment by mericano1** [comment]
or even better just remove the check as it won't work on ajax loaded pages...Do you foresee any issue in doing that?

**Comment by benhoIIand** [comment]
true. i guess the plugin won't be called until the page has loaded, so no, I can't see any reason for the check to be there. thanks for the advice

**Comment by benhoIIand** [comment]
I have removed the function. let me know if that causes any issue (it shouldn't)
