### ISSUE TITLE
Can accordion slide?

### ISSUE THREAD

**Issue by berchman** [benhoIIand/Slidorion#11]
Hi, wanting to use your work but I have a special need. I have more titles than can display in the vertical space (15).
I want to have all the functionality that you provide, however would it be possible to make the entire "sidebar-accordion" section scroll vertically within that space?

In other words only 7-9 titles are displayed, but there are 15 available and you would have to scroll vertically to see all.

Let me know if you have any questions.

**Comment by benhoIIand** [comment]
Hi,

I think I understand what you want to do. if you change the css of #accordion with:

``` css
#accordion {
    overflow-y: scroll;
}
```

that should be what you're looking for

**Comment by berchman** [comment]
Hi Ben,
Thanks so much for the reply.
I'll give that a try. It will definitely get me going, and if/when I do get it working how I need I'll be sure to drop you a note to take a look.
Many thanks,
Bert

**Comment by berchman** [comment]
Hi Ben,
Been working away on a site using your tool and have a question.
First, I did get the slider to "slide" vertically within the accordion.
See here: http://igsfilm.com/home/  (dev site)

you'll notice on the right of the slider is an accordion of text that auto-plays, or you can click on it to go where you like.

When its playing on auto-pilot, and reaches the bottom slides, you cannot see the content.

I'm looking for a tweak that would auto-slide the slideshow "up" when it gets to those that are down at the bottom so you can read it. Then when it loops back to the top it would slide back down.

The functionality works when you click on the bottom title. Everything moves up like it should, it just doesn't happen in the auto-pilot flow.

Let me know what you think.

Thanks,
Bert

**Comment by benhoIIand** [comment]
I can't think of a quick and easy solution except to reduce the number of links on the right or increase the height of the Slidorion container, or even just the accordion. I can't think of any reason why that wouldn't work.

**Comment by berchman** [comment]
Cool thanks Ben!
Just hit the paypal. :-)

On Mar 5, 2012, at 1:30 AM, hollandben wrote:

> I can't think of a quick and easy solution except to reduce the number of links on the right or increase the height of the Slidorion container, or even just the accordion. I can't think of any reason why that wouldn't work.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hollandben/Slidorion/issues/11#issuecomment-4319259

Thanks,

## Bert 

Bert Mahoney AIGA

Bespoke WordPress Websites
http://www.berchman.com

AIGA | the professional association for design
