### ISSUE TITLE
Auto-set height of link-content

### ISSUE THREAD

**Issue by janjouketjalsma** [benhoIIand/Slidorion#15]
Hi I added this just after the initialisation of slidorion to auto-adapt to the number of slides and the padding and margin of the link-header and the link-content. I think this feature could help a lot of users since the number of slides does not matter anymore.

In my case I fill the slider automatically from a CMS. Sometimes there are 3 slides sometimes only one, now slidorion always displays correctly.

```
var accordionOuterHeight = $("#accordion").outerHeight();
var linkHeaderHeights = 0;
$(".link-header").each(function() {
    linkHeaderHeights += $(this).outerHeight();
});
var slideContentHeightMargin = $(".link-content").outerHeight() - $(".link-content").height();
var slideHeight = accordionOuterHeight - linkHeaderHeights - slideContentHeightMargin;
$(".link-content").css("height", slideHeight);
```

**Comment by quickwick** [comment]
Thank you so much! I was having a problem with an 8-slide slider, where the bottom link header was getting cut off on Firefox and IE but displaying correctly in Chrome and Safari. With your extra JS, all the link headers are now displaying correctly in all four browsers. Well, IE displays a small amount of extra white space under the bottom link header, but I can live with that compared to how it looked before.

**Comment by janjouketjalsma** [comment]
You're welcome!
