### ISSUE TITLE
Allow for Back and Forward buttons

### ISSUE THREAD

**Issue by mlhess** [benhoIIand/Slidorion#16]
It would be very helpful if we could have back and forward buttons.  So if you are on slide 5, and you press forward, you end up on 6.

**Comment by benhoIIand** [comment]
Back and forward buttons have been added. You can access these by using the following options:

controlNav (boolean) - turns on the navigation controls
controlNavClass (string) - the class for the navigation buttons

'-left- and '-right' are added to the class name

this update was added in version 1.1

http://www.slidorion.com/demos/slidorion-navigation.html
