### ISSUE TITLE
Can't inset image into posts

### ISSUE THREAD

**Issue by slaax** [benhoIIand/Slidorion#17]
After installing the slidorion plugin for wordpress I am no longer able to insert images onto regular posts. I do not get any kind of error while uploading and inserting an image from my computer the media overlay just closes when i click insert into post.

But if I try to do it from an URL i get this error message:

Uncaught TypeError: Cannot read property '0' of null slidorion_uploader.js:5
send_to_editor slidorion_uploader.js:5
addExtImage.insert media-upload.php:100
onclick media-upload.php:216

The plugin version is 1.0.2

I am rather new to wordpress but it looks like the problem is that it is overwriting WordPress's core functionality.

**Comment by benhoIIand** [comment]
The WordPress plugin is not longer supported - sorry
