### ISSUE TITLE
Accordion z-index issue

### ISSUE THREAD

**Issue by danallencreative** [benhoIIand/Slidorion#19]
Hi Ben, like with almost everyone else who has got hold of the slidorion, we think its brilliant.

What I am looking to do with it is stretch out the image and have the accordion hover over. http://shop.nordstrom.com/ has the style i like for reference.

I had looked into the css and while the accordion does have the z-index in place, it still fails to achieve such hovering over the slider div. As i am pretty basic with css my apologies in advance if the resolution is simple.

Many thanks
Dan

**Comment by benhoIIand** [comment]
I will create an example shortly of how to do this

**Comment by benhoIIand** [comment]
Here is an example of your problem (I think). It is done by setting the 'slider' element as full width and height of the slidorion itself. Then set the accordion as absolute, and position it where you need it.

http://www.slidorion.com/demos/slidorion-inset.html

This the stylesheet you can look at to see the changes. I would recommend using these in your main styles.

http://www.slidorion.com/css/inset.css

Hope that helps?
