### ISSUE TITLE
accordion auto loop and slide accordingly?

### ISSUE THREAD

**Issue by esthercheng** [benhoIIand/Slidorion#20]
Hi, just wondering if there anyway we can change the code such that, when the accordion is showing click, the current click image will be appended to the last in the accordion list and pushing up the next in accordion to the top. This enable the accordion to auto slide as well as looping.

Because my accordion is set to a limited size, and those in the overflow cant shift up. 

Thanks appreciate  help

**Comment by benhoIIand** [comment]
This isn't a feature I'm looking to implement. Feel free to fork the repo and give it a crack
