### ISSUE TITLE
The number of slider images does not match the number of accordion sections.

### ISSUE THREAD

**Issue by BenRacicot** [benhoIIand/Slidorion#23]
Hello! Great work on the Slidorian. I was hoping to place videos inside of it will it support YT or Vimeo embeds?

The problem is: the demo and my attempt at using Slidorian gives me:
"The number of slider images does not match the number of accordion sections."

What could create this error? The markup is correct and there is in fact the same number of image divs as accordion sections. 
Thanks for your time with it.

**Comment by benhoIIand** [comment]
The error is pretty self-explanatory.

It means that the number of slides `.slide` and the number of accordions `.link-header` don't match. Makes sure you have an equal number of slides and accordion sections

**Comment by BenRacicot** [comment]
Hmm, this is what I have:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<script src="js/jquery.easing.js"></script>

<script src="js/jquery.slidorion.min.js"></script>

<link rel="stylesheet" href="css/slidorion.css" />

```
<script>
    $(document).ready(function(){
        $('#slidorion').slidorion({
            speed: 1000,
            interval: 4000,
            effect: 'slideLeft'
        });
    });
</script>



<div id="header"><h1>SLIDORION</h1></div>

<div id="slidorion">

    <div id="slider">
        <div class="slide-image" rel="section1">
            <img src="img/kung-fu-panda.jpg" width="400" height="320" />
        </div>
        <div class="slider-image" rel="section2">
            <img src="img/the-dark-knight.jpg" width="488" height="400" />
        </div>
        <div class="slider-image" rel="section3">
            <img src="img/hot-fuzz.jpg" width="488" height="400" />
        </div>
    </div>

    <div id="accordion">

        <div class="header"><a class="slider-link" rel="section1">Kung Fu Panda 2</a></div>
        <div class="content">
            <p>In the Valley of Peace, Po Ping is revelling in his fulfilled dreams as he serves as the fabled Dragon Warrior protecting his home with his heroes now his closest friends. However, Po and company learn that the murderous Lord Shen of Gongman City is threatening the land with a fearsome new weapon that could mean the end of kung fu forever.</p>
            <a href="http://www.imdb.com/title/tt1302011/">Read more</a>
        </div>

        <div class="header"><a class="slider-link" rel="section2">The Dark Knight</a></div>
        <div class="content">
            <p>Batman raises the stakes in his war on crime. With the help of Lieutenant Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the city streets. But they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as The Joker.</p>
            <a href="http://www.imdb.com/title/tt0468569/">Read more</a>
        </div>

        <div class="header"><a class="slider-link" rel="section3">Hot Fuzz</a></div>
        <div class="content">
            <p>Top London cop, PC Nicholas Angel is good. Too good. And to stop the rest of his team looking bad, he is reassigned to the quiet town of Sandford. Everything seems quiet for Angel, until two actors are found decapitated. It is called an accident, but Angel isn't going to accept that, especially when more and more people turn up dead.</p>
            <a href="http://www.imdb.com/title/tt0425112/">Read more</a>
        </div>

    </div>
</div>
```

**Comment by benhoIIand** [comment]
you need to keep the classes `link-header` and `slide`. you've changed them to `header` and `slider-image`

**Comment by BenRacicot** [comment]
Oh! That's how it came out of the box here on git. The slides animate but the panel is still broken that way. Is there anything else you can think of?

Thanks again for your time.

**Comment by benhoIIand** [comment]
open dev tools in Chrome (F12) or Firebug and check the console. not much I can help you with unless you can point me at a demo

**Comment by BenRacicot** [comment]
Hey Ben,
I threw it up on http://zorkboy.com wheneve ryou may have time for it of course.
I can't see anything wrong in my console but I am a bit green at web dev.

**Comment by benhoIIand** [comment]
the link you provided requires a username and password

**Comment by BenRacicot** [comment]
I didn't realize so sorry. It's off now

**Comment by benhoIIand** [comment]
use the class `link-content` instead of `content`. that will sort it

**Comment by BenRacicot** [comment]
That did it! Thank you for your help. I'll be following

**Comment by benhoIIand** [comment]
not a problem. give me a shout if there's anything else you need
