### ISSUE TITLE
How to add a fourth acoordion

### ISSUE THREAD

**Issue by SergioTM** [benhoIIand/Slidorion#28]
Hi
Your Slidorin is really a pretty carousels but I wonder how to made a litle change:
by default Slidorin has 3 titles, how can I add 2 more???  I need 5 titles and 5 contents, I got no expertice with jscript, can anyone tell me where to change 

thnaks in advance

**Comment by benhoIIand** [comment]
Check out this blog post I wrote. Should help you out

http://benholland.me/tutorials/slidorion-tutorial-adding-new-section/

**Comment by leosur** [comment]
my slidorion has 15 titles, all the tabs are present but only rotate the first 10 and then move to #1 again... never move to show 11 thru 15?
