### ISSUE TITLE
z-index goes up infinitely

### ISSUE THREAD

**Issue by fsalomon** [benhoIIand/Slidorion#31]
As of right now, when the slider is playing, the z-indexes are incremented by one each time. This causes problems when there is something that needs to be displayed on top of the slider either temporarily or permanently. For example a nested menu on top of the slider. The css rule for the menu will state a static z-index and if the slider plays for long enough it will result in an undesirable layout. Sure, this can be fixed by choosing a very big z-index for the static stuff, but there really seems to be no reason to increment the z-indexes in the way it is currently done. Why not just use two z-indexes for the whole slider? That would be much cleaner.

**Comment by benhoIIand** [comment]
This was fixed in the v1.2 release
