### ISSUE TITLE
SLIDORION version 1.1 problem

### ISSUE THREAD

**Issue by ShiriM** [benhoIIand/Slidorion#32]
Hello Ben,

Slidorion is great! Thanks you for this tool.

I want to use it in my site , but it’s giving me an error in IE8. I read that the issue was resolved in version 0.91 but I have version 1.1 and it is still not working. I really want to use it but I also need it to work under ie8.

Here is the error: 

obj.data("slideCount",sliderCount)

It says  Object doesn't support this property or method  when it’s referring to data.

I use jQuery min file version 1.91.

Can you help me here?

Thank you very much!

**Comment by benhoIIand** [comment]
Can you give me a live link to view?

The support for v1.1 is IE7+, but in v2, it will change to IE8+
