### ISSUE TITLE
function sectionClicked(){

### ISSUE THREAD

**Issue by selinav** [benhoIIand/Slidorion#6]
Hello,

Thanks a lot for this nice plugin. I've noticed the function sectionClicked(){ hide another item of menu of my page which are not in the #slidorion.
To correct it promptly, I have exclude my menu li like below : (.not("#block-system-main-menu li"))

<code>
                function sectionClicked(){
                    $objHeader = $(this);
                    section = $(this).attr('rel');
                    if(section==current){
                        return false;
                    }else{
                        if($objHeader.parent().next().is(':hidden')) {
                            $('.active').removeClass('active').parent().next().not("#block-system-main-menu li").slideUp();
                            $objHeader.addClass('active').parent().next().slideDown();
                        }
                        animation(current, section, effect, speed, easingOption);
                    }
                    zPos++;
                    current = section;
                    return false;
                }
</code>

I think the plugin should verify if it is only in the #slidorion div.

**Comment by benhoIIand** [comment]
Can you change your function so it looks like this (see below) and let me know if that fixes it. Thanks

function sectionClicked(){
    $objHeader = $(this, obj);
    section = $(this, obj).attr('rel');
    if(section==current){
        return false;
    }else{
        if($objHeader.parent().next().is(':hidden')) {
            $('.slider-link.active', obj).removeClass('active').parent().next().slideUp();
                $objHeader.addClass('active').parent().next().slideDown();
        }
        animation(current, section, effect, speed, easingOption);
    }
    zPos++;
    current = section;
    return false;
}

**Comment by selinav** [comment]
Thank you it fixes my problem.
