### ISSUE TITLE
Multiple event handling

### ISSUE THREAD

**Issue by seaburrows** [benhoIIand/Slidorion#7]
There is an issue where if you click the second-to-last tab and then quickly click the last tab, the last description text pops out of the container.

Only checked on Chrome, might be CSS related. The way I noticed it was I happened to click the last tab just as the second-to-last tab was automatically activated.

p.s. liking this plugin!

**Comment by benhoIIand** [comment]
Sorry for the late reply, this should have been fixed with the release of Version 1.0. There were some timing issues
