### ISSUE TITLE
hoverPause issue

### ISSUE THREAD

**Issue by robtho2512** [benhoIIand/Slidorion#8]
When I set the hoverPause to true and click randomly through the accordion t causes the interval  to speed up significantly Any idea what causes this?

**Comment by benhoIIand** [comment]
most probably the timer is starting again after the mouse is moved away, and then the auto play is also continuing and not reseting. i'll get it sorted tonight

**Comment by benhoIIand** [comment]
this has been fixed and is currently live on the website. please re-download

**Comment by robtho2512** [comment]
Thank you so much!
